export const sampleItems = [
  {
    page_type: "blog",
    url: "https://example.com/blogs/news/how-to-choose-a-glider-recliner",
    title: "How to Choose a Glider Recliner",
    meta_description: "A practical guide to choosing nursery seating.",
    h1: "How to Choose a Glider Recliner",
    excerpt: "A practical buying guide for nursery seating.",
    status: "published",
    cluster_name: "Nursery Furniture",
    keyword: "glider recliner",
    raw_html:
      '<h1>How to Choose a Glider Recliner</h1><p>The first paragraph mentions glider recliner but should not receive links.</p><h2>Nursery Seating Basics</h2><p>A comfortable nursery chair can make feeding and reading routines easier for parents.</p><p>Many families compare glider recliner options with rocking chair styles before they shop.</p><p>This paragraph already links to <a href="https://example.com/blogs/news/nursery-layout-ideas">nursery layout ideas</a> and should be skipped.</p><p>Parents often choose nursery furniture that supports long nights and daily care.</p>',
  },
  {
    page_type: "collection",
    url: "https://example.com/collections/glider-recliners",
    title: "Glider Recliners",
    meta_description: "Shop comfortable glider recliners for nursery rooms.",
    h1: "Glider Recliners",
    excerpt: "Comfortable nursery glider recliners.",
    status: "published",
    cluster_name: "Nursery Furniture",
    keyword: "glider recliner",
  },
  {
    page_type: "collection",
    url: "https://example.com/collections/nursery-furniture",
    title: "Nursery Furniture",
    meta_description: "Furniture for modern nursery spaces.",
    h1: "Nursery Furniture",
    excerpt: "Nursery furniture for daily care.",
    status: "published",
    cluster_name: "Nursery Furniture",
    keyword: "nursery furniture",
  },
  {
    page_type: "product",
    url: "https://example.com/collections/chairs/products/cloud-glider-chair",
    title: "Cloud Glider Chair",
    meta_description: "A soft glider chair for nursery rooms.",
    h1: "Cloud Glider Chair",
    excerpt: "A compact nursery chair.",
    status: "published",
    cluster_name: "Nursery Furniture",
    keyword: "nursery chair",
  },
  {
    page_type: "product",
    url: "https://example.com/products/rocking-chair",
    title: "Rocking Chair",
    meta_description: "A classic rocking chair for home routines.",
    h1: "Rocking Chair",
    excerpt: "Classic rocking chair.",
    status: "published",
    cluster_name: "Nursery Furniture",
    keyword: "rocking chair",
  },
  {
    page_type: "blog",
    url: "https://example.com/blogs/news/nursery-layout-ideas",
    title: "Nursery Layout Ideas",
    meta_description: "Plan a practical nursery layout.",
    h1: "Nursery Layout Ideas",
    excerpt: "Ideas for nursery layout planning.",
    status: "published",
    cluster_name: "Nursery Furniture",
    keyword: "nursery layout ideas",
  },
  {
    page_type: "blog",
    url: "https://example.com/blogs/news/feeding-chair-guide",
    title: "Feeding Chair Guide",
    meta_description: "Choose a feeding chair for daily care.",
    h1: "Feeding Chair Guide",
    excerpt: "Guide to choosing feeding chairs.",
    status: "published",
    cluster_name: "Nursery Furniture",
    keyword: "feeding chair",
  },
  {
    page_type: "blog",
    url: "https://example.com/blogs/news/rocking-chair-vs-glider",
    title: "Rocking Chair vs Glider",
    meta_description: "Compare rocking chair and glider styles.",
    h1: "Rocking Chair vs Glider",
    excerpt: "Compare common nursery seating options.",
    status: "published",
    cluster_name: "Nursery Furniture",
    keyword: "rocking chair",
  },
];

export const sampleJson = JSON.stringify({ items: sampleItems }, null, 2);
